package chat.auth.model

import kotlinx.serialization.Serializable

@Serializable
data class Vehicle (
    val id: Int,
    val address: String,
    val latitude: String,
    val longitude: String,
    val shareLocation: Int,
    val lgaId:Int,
    val cityId:Int,
    val stateId: Int,
    val title: String,    //   Title
    val description: String,
    val model: Int,
    val make: Int,
    val year:  Int,
    val vehTypeId: Int,
    val vehUseId: Int,
    val vehSubTypeId: Int,
    val powerSource: Int,   // Petrol, Diesel, Gas, Electric, Hybrid, Solar
    val typeId: Int,
    val enteredDate: String,
    val expiryDate: String,
    val userId: Int,
    val marketedByUserid: Int,
    val marketedByPhone: String,
    val marketedByEmail: String,
    val statusId: Int,
    val orderId: Int,
    val img1: String,
    val img2: String,
    val img3: String,
    val img4: String,
    val img5: String,
    val img6: String,
    val img7: String,
    val img8: String,
    val img9: String,
    val img10: String,
    val video1: String,
    val video2: String,
    val cylinders: Int,
    val odometer: Int,
    val transmission: Int,
    val displayAddress: Int,
    val priceMain: Long,
    val pricePrecision : Int,
    val priceCurrency : String,
    val vehicleLogo : String,
    val vehicleLogoID : Int,
    val makeModelYearStr: String,
    val rowId: String,
    val marketedByImage: String
)
